// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BadgeNumber          int32    `protobuf:"varint,2,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	VacationAccrualRate  float32  `protobuf:"fixed32,5,opt,name=vacationAccrualRate,proto3" json:"vacationAccrualRate,omitempty"`
	VacationAccrued      float32  `protobuf:"fixed32,6,opt,name=vacationAccrued,proto3" json:"vacationAccrued,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetVacationAccrualRate() float32 {
	if m != nil {
		return m.VacationAccrualRate
	}
	return 0
}

func (m *Employee) GetVacationAccrued() float32 {
	if m != nil {
		return m.VacationAccrued
	}
	return 0
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type GetByBadgeNumberRequest struct {
	BadgeNumber          int32    `protobuf:"varint,1,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBadgeNumberRequest) Reset()         { *m = GetByBadgeNumberRequest{} }
func (m *GetByBadgeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBadgeNumberRequest) ProtoMessage()    {}
func (*GetByBadgeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *GetByBadgeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBadgeNumberRequest.Unmarshal(m, b)
}
func (m *GetByBadgeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBadgeNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetByBadgeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBadgeNumberRequest.Merge(m, src)
}
func (m *GetByBadgeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBadgeNumberRequest.Size(m)
}
func (m *GetByBadgeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBadgeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBadgeNumberRequest proto.InternalMessageInfo

func (m *GetByBadgeNumberRequest) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

type EmployeeRequest struct {
	Employeee            *Employee `protobuf:"bytes,1,opt,name=employeee,proto3" json:"employeee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmployeee() *Employee {
	if m != nil {
		return m.Employeee
	}
	return nil
}

type EmployeeResponse struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type AddPhotoRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoRequest) Reset()         { *m = AddPhotoRequest{} }
func (m *AddPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*AddPhotoRequest) ProtoMessage()    {}
func (*AddPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *AddPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoRequest.Unmarshal(m, b)
}
func (m *AddPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoRequest.Marshal(b, m, deterministic)
}
func (m *AddPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoRequest.Merge(m, src)
}
func (m *AddPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_AddPhotoRequest.Size(m)
}
func (m *AddPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoRequest proto.InternalMessageInfo

func (m *AddPhotoRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddPhotoResponse struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=isOk,proto3" json:"isOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoResponse) Reset()         { *m = AddPhotoResponse{} }
func (m *AddPhotoResponse) String() string { return proto.CompactTextString(m) }
func (*AddPhotoResponse) ProtoMessage()    {}
func (*AddPhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *AddPhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoResponse.Unmarshal(m, b)
}
func (m *AddPhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoResponse.Marshal(b, m, deterministic)
}
func (m *AddPhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoResponse.Merge(m, src)
}
func (m *AddPhotoResponse) XXX_Size() int {
	return xxx_messageInfo_AddPhotoResponse.Size(m)
}
func (m *AddPhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoResponse proto.InternalMessageInfo

func (m *AddPhotoResponse) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func init() {
	proto.RegisterType((*Employee)(nil), "Employee")
	proto.RegisterType((*GetAllRequest)(nil), "GetAllRequest")
	proto.RegisterType((*GetByBadgeNumberRequest)(nil), "GetByBadgeNumberRequest")
	proto.RegisterType((*EmployeeRequest)(nil), "EmployeeRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "EmployeeResponse")
	proto.RegisterType((*AddPhotoRequest)(nil), "AddPhotoRequest")
	proto.RegisterType((*AddPhotoResponse)(nil), "AddPhotoResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0xae, 0x93, 0x40,
	0x14, 0x86, 0x33, 0xc8, 0xad, 0x70, 0xea, 0x2d, 0xdc, 0x71, 0x21, 0x69, 0x5c, 0x10, 0x92, 0x2a,
	0x89, 0xc9, 0xd8, 0xb4, 0x2b, 0x75, 0x61, 0xda, 0xc4, 0x74, 0x57, 0x0d, 0xdd, 0xb9, 0x1b, 0x98,
	0x63, 0x25, 0x42, 0x07, 0x99, 0x69, 0x93, 0x3e, 0x88, 0x2f, 0xe6, 0x13, 0x99, 0x8e, 0x50, 0x2c,
	0xad, 0xc9, 0xdd, 0x0d, 0xe7, 0xff, 0x7e, 0x86, 0xf3, 0x25, 0xc0, 0xa8, 0x44, 0xa5, 0xf8, 0x16,
	0x15, 0xab, 0x6a, 0xa9, 0x65, 0xf4, 0x9b, 0x80, 0xf3, 0xa9, 0xac, 0x0a, 0x79, 0x44, 0xa4, 0x23,
	0xb0, 0x72, 0x11, 0x90, 0x90, 0xc4, 0x77, 0x89, 0x95, 0x0b, 0x1a, 0xc2, 0x30, 0xe5, 0x62, 0x8b,
	0xeb, 0x7d, 0x99, 0x62, 0x1d, 0x58, 0x26, 0xf8, 0x77, 0x44, 0x5f, 0x82, 0xfb, 0x2d, 0xaf, 0x95,
	0x5e, 0xf3, 0x12, 0x83, 0x27, 0x21, 0x89, 0xdd, 0xa4, 0x1b, 0xd0, 0x31, 0x38, 0x05, 0x6f, 0x42,
	0xdb, 0x84, 0xe7, 0x67, 0x3a, 0x85, 0xe7, 0x07, 0x9e, 0x71, 0x9d, 0xcb, 0xdd, 0x22, 0xcb, 0xea,
	0x3d, 0x2f, 0x12, 0xae, 0x31, 0xb8, 0x0b, 0x49, 0x6c, 0x25, 0xb7, 0x22, 0x1a, 0x83, 0x77, 0x31,
	0x46, 0x11, 0x0c, 0x0c, 0xdd, 0x1f, 0x47, 0x1e, 0xdc, 0xaf, 0x50, 0x2f, 0x8a, 0x22, 0xc1, 0x9f,
	0x7b, 0x54, 0x3a, 0xfa, 0x00, 0x2f, 0x56, 0xa8, 0x97, 0xc7, 0x65, 0xf7, 0xe9, 0x4d, 0xd4, 0xdf,
	0x91, 0x5c, 0xed, 0x18, 0xbd, 0x07, 0xaf, 0x35, 0xd4, 0x96, 0x5e, 0x83, 0x8b, 0xcd, 0x08, 0x4d,
	0x65, 0x38, 0x73, 0xd9, 0x19, 0xea, 0xb2, 0xe8, 0x1d, 0xf8, 0x5d, 0x57, 0x55, 0x72, 0xa7, 0x90,
	0x4e, 0xc0, 0x69, 0x81, 0xeb, 0xee, 0x39, 0x8a, 0x26, 0xe0, 0x2d, 0x84, 0xf8, 0xf2, 0x5d, 0x6a,
	0xd9, 0x5e, 0x4b, 0xc1, 0x16, 0x5c, 0x73, 0xd3, 0x7a, 0x96, 0x98, 0x73, 0xf4, 0x0a, 0xfc, 0x0e,
	0x6b, 0x6e, 0xa0, 0x60, 0xe7, 0xea, 0xf3, 0x0f, 0xc3, 0x39, 0x89, 0x39, 0xcf, 0x7e, 0x59, 0xdd,
	0x1a, 0x1b, 0xac, 0x0f, 0x79, 0x86, 0xf4, 0x23, 0xf8, 0x7d, 0x2d, 0x34, 0x60, 0xff, 0x31, 0x35,
	0x7e, 0x60, 0x57, 0xab, 0xbc, 0x81, 0xc1, 0x5f, 0xd1, 0x74, 0xc4, 0x2e, 0x8c, 0xdf, 0x86, 0xed,
	0x0d, 0x3f, 0x20, 0xf5, 0x59, 0x4f, 0xe7, 0x2d, 0x78, 0x06, 0x4f, 0x4f, 0xf0, 0xe9, 0xd5, 0x8f,
	0xe1, 0x63, 0x32, 0x25, 0x74, 0x0e, 0x4e, 0xab, 0x82, 0xfa, 0xac, 0x27, 0x6f, 0xfc, 0xc0, 0xfa,
	0x9e, 0x4e, 0xa5, 0xe5, 0xfd, 0xd7, 0xe1, 0xb6, 0xae, 0x32, 0x81, 0xa5, 0x7c, 0x5b, 0xa5, 0xe9,
	0xc0, 0xfc, 0x16, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe1, 0x72, 0x6b, 0x28, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error)
	AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_AddPhotoClient, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/GetByBadgeNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) Save(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/EmployeeService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServiceClient) SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_SaveAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[0], "/EmployeeService/SaveAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceSaveAllClient{stream}
	return x, nil
}

type EmployeeService_SaveAllClient interface {
	Send(*EmployeeRequest) error
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServiceSaveAllClient struct {
	grpc.ClientStream
}

func (x *employeeServiceSaveAllClient) Send(m *EmployeeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceSaveAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServiceClient) AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeService_AddPhotoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeService_serviceDesc.Streams[1], "/EmployeeService/AddPhoto", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceAddPhotoClient{stream}
	return x, nil
}

type EmployeeService_AddPhotoClient interface {
	Send(*AddPhotoRequest) error
	Recv() (*AddPhotoResponse, error)
	grpc.ClientStream
}

type employeeServiceAddPhotoClient struct {
	grpc.ClientStream
}

func (x *employeeServiceAddPhotoClient) Send(m *AddPhotoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServiceAddPhotoClient) Recv() (*AddPhotoResponse, error) {
	m := new(AddPhotoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetByBadgeNumber(context.Context, *GetByBadgeNumberRequest) (*EmployeeResponse, error)
	GetAll(context.Context, *GetAllRequest) (*EmployeeResponse, error)
	Save(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	SaveAll(EmployeeService_SaveAllServer) error
	AddPhoto(EmployeeService_AddPhotoServer) error
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetByBadgeNumber(ctx context.Context, req *GetByBadgeNumberRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByBadgeNumber not implemented")
}
func (*UnimplementedEmployeeServiceServer) GetAll(ctx context.Context, req *GetAllRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedEmployeeServiceServer) Save(ctx context.Context, req *EmployeeRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedEmployeeServiceServer) SaveAll(srv EmployeeService_SaveAllServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveAll not implemented")
}
func (*UnimplementedEmployeeServiceServer) AddPhoto(srv EmployeeService_AddPhotoServer) error {
	return status.Errorf(codes.Unimplemented, "method AddPhoto not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetByBadgeNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBadgeNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetByBadgeNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/GetByBadgeNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetByBadgeNumber(ctx, req.(*GetByBadgeNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EmployeeService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Save(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeService_SaveAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).SaveAll(&employeeServiceSaveAllServer{stream})
}

type EmployeeService_SaveAllServer interface {
	Send(*EmployeeResponse) error
	Recv() (*EmployeeRequest, error)
	grpc.ServerStream
}

type employeeServiceSaveAllServer struct {
	grpc.ServerStream
}

func (x *employeeServiceSaveAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceSaveAllServer) Recv() (*EmployeeRequest, error) {
	m := new(EmployeeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EmployeeService_AddPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServiceServer).AddPhoto(&employeeServiceAddPhotoServer{stream})
}

type EmployeeService_AddPhotoServer interface {
	Send(*AddPhotoResponse) error
	Recv() (*AddPhotoRequest, error)
	grpc.ServerStream
}

type employeeServiceAddPhotoServer struct {
	grpc.ServerStream
}

func (x *employeeServiceAddPhotoServer) Send(m *AddPhotoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServiceAddPhotoServer) Recv() (*AddPhotoRequest, error) {
	m := new(AddPhotoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByBadgeNumber",
			Handler:    _EmployeeService_GetByBadgeNumber_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _EmployeeService_GetAll_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _EmployeeService_Save_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveAll",
			Handler:       _EmployeeService_SaveAll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AddPhoto",
			Handler:       _EmployeeService_AddPhoto_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messages.proto",
}
